root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main cmd/server/main.go"
  
  bin = "./tmp/main"
  
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend"]
  delay = 1000

[log]
  time = true

[misc]
  clean_on_exit = true